name: Publish to WordPress.org
on:
    release:
        types: [released]
jobs:
    tag:
        name: New Release
        runs-on: ubuntu-latest
        env:
            SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        steps:
            - uses: act10ns/slack@v2
              with:
                  status: starting
              if: ${{ always() }}
            - name: Checkout code
              uses: actions/checkout@v3
            - name: Setup Node.js environment
              uses: actions/setup-node@v2.5.2
              with:
                node-version-file: .nvmrc
            - name: Build Plugin
              uses: ./.github/actions/make-build
            - name: WordPress Plugin Deploy
              id: deploy
              uses: 10up/action-wordpress-plugin-deploy@stable
              env:
                  SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
                  SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
                  SLUG: rave-payment-forms
            - name: push build status to Slack
              uses: 8398a7/action-slack@v3
              with:
                  status: ${{ job.status }}
                  fields: repo,message,commit,author,action,eventName,ref,workflow,job,took,pullRequest
              env:
                  SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
              if: always()
